Enh/class parachute
Projeto-Jupiter/RocketPy pull request #113
Opened 2021-11-25 06:08 UTC by FranzYuri

## Pull request type

Please check the type of change your PR introduces:

- [X] Code base additions (bugfix, features)
- [ ] Code maintenance (refactoring, formatting, renaming, tests)
- [ ] ReadMe, Docs and GitHub maintenance
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- ReadMe, Docs and GitHub maintenance:

  - [ ] Spelling has been verified
  - [ ] Code docs are working correctly 

- Code base maintenance (refactoring, formatting, renaming):

  - [ ] Docs have been reviewed and added / updated if needed
  - [ ] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [ ] All tests (`pytest --runslow`) have passed locally

- Code base additions (for bug fixes / features):

  - [ ] Tests for the changes have been added
  - [ ] Docs have been reviewed and added / updated if needed
  - [X] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [X] All tests (`pytest --runslow`) have passed locally

## What is the current behavior?

Currently parachutes are types inside class Parachute.

## What is the new behavior?

Now, there is a separated class for parachutes.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

Enter text here...

2021-12-07 11:38 UTC, Gui-FernandesBR requested changes
Awesome! It was a both simple and good pull request, I liked it. I have some commentaries asking for changes, hope you enjoy it in order to improve your code

2021-12-07 11:38 UTC, Gui-FernandesBR commented on rocketpy/Parachute.py
> +Parachute attributes:
Ident correction @FranzYuri

2021-12-07 11:38 UTC, Gui-FernandesBR commented on rocketpy/Parachute.py
> +
Could you define a return? @FranzYuri

2021-12-07 11:38 UTC, Gui-FernandesBR commented on rocketpy/Flight.py
> +from .Parachute import Parachute
I believe it's not necessary here

2022-01-04 22:53 UTC, Gui-FernandesBR commented
@FranzYuri just following-up, it's your turn,
please let me know if you need any help ;)

@Projeto-Jupiter/public-relations-outreach , tests are failling, doeas "build errored" mean that the problem is regarding the constructor?

2022-01-05 02:17 UTC, giovaniceotto commented
In the test log, available here, we can see what the build error actually was: https://app.travis-ci.com/github/Projeto-Jupiter/RocketPy/builds/242391123

![image](https://user-images.githubusercontent.com/572483/148150110-872439c1-60d4-4d44-904a-1b34d7c3c517.png)

This means the style isn't following black. So we need to run black and commit again.

2022-01-05 10:07 UTC, Gui-FernandesBR commented
Tks Gio!!

@FranzYuri it's a simple formatting problem, do you remeber how to run black foratting? If not please contact us or the @Projeto-Jupiter/back-end team and we definitely can help

2022-01-06 18:15 UTC, PatrickSampaioUSP commented on rocketpy/Parachute.py
> +        noise : tuple, list, optional
Shouldn't the noise be optional? I think it is missing a:

`noise=(0, 0, 0)`

2022-01-07 07:24 UTC, FranzYuri commented
Of course. But about that, I had already talked with Kierulff about how for
some reason even running black.py this error is occurring. I will run it
again and see if this issue is still occurring.

On Wed, Jan 5, 2022, 08:07 Guilherme Fernandes Alves <
***@***.***> wrote:

> Tks Gio!!
>
> @FranzYuri <https://github.com/FranzYuri> it's a simple formatting
> problem, do you remeber how to run black foratting? If not please contact
> us or the @Projeto-Jupiter/back-end
> <https://github.com/orgs/Projeto-Jupiter/teams/back-end> team and we
> definitely can help
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Projeto-Jupiter/RocketPy/pull/113#issuecomment-1005547092>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUUG5QEDAC4DBEWP7BL3GDDUUQJ73ANCNFSM5IXWNVVQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-07 07:25 UTC, FranzYuri commented
Indeed, thank you.

On Thu, Jan 6, 2022, 16:15 Patrick Sampaio ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In rocketpy/Parachute.py
> <https://github.com/Projeto-Jupiter/RocketPy/pull/113#discussion_r779758158>
> :
>
> > +    ):
> +        """Initializes Parachute class.
> +        Parameters
> +        ----------
> +        name : string
> +            Name of the parachute.
> +        CdS : float
> +            CdS of the parachute.
> +        Trigger : function
> +            Trigger function.
> +        samplngRate : float
> +            Sampling rate, in hertz, for the Trigger function.
> +        lag : float
> +            Time, in seconds, between the parachute ejection system is triggered and the
> +        parachute is fully opened.
> +        noise : tuple, list, optional
>
> Shouldn't the noise be optional? I think it is missing a:
>
> noise=(0, 0, 0)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Projeto-Jupiter/RocketPy/pull/113#pullrequestreview-845918224>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUUG5QEMGZBCAACCV5JANVDUUXL4ZANCNFSM5IXWNVVQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-12 03:55 UTC, Gui-FernandesBR approved these changes
For me it's already good enough to be merged!!

@PatrickSampaioUSP can you re-review this one and then merge if ready? 
tks!

btw great job @FranzYuri , I hope this starts a good development in terms of recovery on RocketPy

2022-02-17 21:38 UTC, merged