Workin travis script
Projeto-Jupiter/RocketPy pull request #77
Opened 2021-08-04 18:33 UTC by PatrickSampaioUSP

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`python setup.py install`) was run locally and any changes were pushed
- [x] Lint (`black rocketpy`) has passed locally and any fixes were made for failures
- [x] All tests (`pytest --runslow`) have passed locally

## Pull request type
 
 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): 

## What is the current behavior?

RocketPy's code did not have any unit tests setup.

## What is the new behavior?

- Modified `verify-lint` script for using flake8 to verify black linter rules

2021-08-04 18:33 UTC, PatrickSampaioUSP commented
@giovaniceotto

2021-08-05 00:17 UTC, giovaniceotto commented on rocketpy/Function.py
> +        """ "Calculate polynomail coefficients that fit the data exactly."""
Remove extra double quotes `"`.

2021-08-05 00:17 UTC, giovaniceotto requested changes

2021-08-05 00:17 UTC, giovaniceotto commented on rocketpy/Function.py
> +        """ "Calculate polynomail coefficients that fit the data exactly."""
Remove extra double quotes ".

2021-08-07 19:19 UTC, giovaniceotto approved these changes

2021-08-07 19:41 UTC, merged